// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tenis.Models;

namespace Tenis.Migrations
{
    [DbContext(typeof(TenisDbContext))]
    [Migration("20190914185555_relation_db")]
    partial class relation_db
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tenis.Models.Fields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("Tenis.Models.Games", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<int?>("FieldId");

                    b.Property<string>("Score");

                    b.Property<string>("Status");

                    b.Property<int?>("User1IdId");

                    b.Property<int?>("User2IdId");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("User1IdId");

                    b.HasIndex("User2IdId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Tenis.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<int>("UserRole");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tenis.Models.UserDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hand");

                    b.Property<int>("Level");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("UserDetails");
                });

            modelBuilder.Entity("Tenis.Models.Games", b =>
                {
                    b.HasOne("Tenis.Models.Fields", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId");

                    b.HasOne("Tenis.Models.User", "User1Id")
                        .WithMany()
                        .HasForeignKey("User1IdId");

                    b.HasOne("Tenis.Models.User", "User2Id")
                        .WithMany()
                        .HasForeignKey("User2IdId");
                });
#pragma warning restore 612, 618
        }
    }
}
